"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Table = exports.useTable = void 0;
var useTable_1 = require("./useTable");
Object.defineProperty(exports, "useTable", { enumerable: true, get: function () { return useTable_1.default; } });
var Table_1 = require("./Table");
Object.defineProperty(exports, "Table", { enumerable: true, get: function () { return Table_1.Table; } });
//export {default as TableService} from './service';
//export * from './datagrid/interface';
//export {default as ReactDataGrid} from './datagrid/ReactDataGrid';
// export {default as CustomColumnTable} from './muitable/CustomColumnTable';
// export {default as CustomStyleTable} from './muitable/CustomStyleTable';
// export {default as RawClickMuiTable} from './muitable/RawClickMuiTable';
//export * from './muitable/interface';
